### ISSUE TITLE
[BUG] Autocomplete not working for airport ICAO codes.

### ISSUE THREAD

**Issue by cviper13** [Zedruc/24planner#3]
When creating a new flight, on the textboxes you typed the ICAO code when you click on the autocomplete/dropdown selections, it doesn't autocomplete that one.

**Steps to reproduce:**
* Enter the 24 Planner
* Create a new plan
* Enter the first 3, 2 or 1st letter of an airport
* Click it on the dropdown menu, it doesnt autocomplete that.

**Comment by FormicAcidGD** [comment]
unplug your mouse

**Comment by FormicAcidGD** [comment]
I fixed it, zedruc totally did not forget to emit the change when you actually clicked it 👍
